// src/app/components/alert/alert.component.ts
import { Component, Input } from '@angular/core';
import { Observable } from 'rxjs';

@Component({
  selector: 'blue-alert',
  templateUrl: './alert.component.html',
  styleUrls: ['./alert.component.scss']
})
export class AlertComponent {
  @Input() alerts: Array<any>;
}

<div class="card card-inverse alert-card mb-3" [ngClass]="'card-' + alert.theme" *ngFor="let alert of alerts">
  <div class="card-block">
    <blockquote class="card-blockquote d-flex flex-row justify-content-start align-items-center">
      <div class="display-1"><i class="fa fa-fw" [ngClass]="'fa-' + alert.icon"></i></div>
      <div>
        <h3 class="text-uppercase">{{ alert.title }}</h3>
        <span>{{ alert.content }}</span>
      </div>
    </blockquote>
  </div>
</div>

// src/components/Alert.vue
<template>
  <div id="alert">
    <div class="card sense-card mb-3">
      <div class="card-body text-white" v-bind:class="['bg-'+color]">
        <blockquote class="card-blockquote d-flex flex-row align-items-center my-1">
          <div class="d-flex flex-col">
            <check-icon size="100"></check-icon>
          </div>
          <div class="ml-3">
            <h3 class="text-uppercase">{{ title }}</h3>
            <span>{{ content }}</span>
          </div>
        </blockquote>
      </div>
    </div>
  </div>
</template>

<script lang="ts">
import { Component, Prop, Vue } from "vue-property-decorator";
import { CheckIcon } from "vue-feather-icons";

@Component({
  components: { CheckIcon }
})
export default class Alerts extends Vue {
  @Prop({ default: "" }) readonly title!: string;
  @Prop({ default: "" }) readonly content!: string;
  @Prop({ default: "" }) readonly color!: string;
}
</script>

<style scoped lang="scss">
.sense-alert-icon {
  display: block;
  height: 100%;
}
</style>
